-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jul 22, 2023 at 03:22 PM
-- Server version: 8.0.31
-- PHP Version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `vert_galant`
--

-- --------------------------------------------------------

--
-- Table structure for table `actualites`
--

DROP TABLE IF EXISTS `actualites`;
CREATE TABLE IF NOT EXISTS `actualites` (
  `id_actualite` int NOT NULL AUTO_INCREMENT,
  `titre` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `texte` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `date` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id_actualite`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `actualites`
--

INSERT INTO `actualites` (`id_actualite`, `titre`, `texte`, `date`) VALUES
(6, 'ECOLOGIE : CAMILLE ETIENNE - LE 22 JUILLET A 19H00', 'Un essai qui dépasse les clivages pour appeler à un soulèvement écologique intergénérationnel, sensible, et radical, porté par la désobéissance. \"Sortir de notre impuissance. C’est tout l', '16-07-2023'),
(4, 'LITTÉRATURE DE L\'IMAGINAIRE : EMMANUEL BRAULT ET NICOLAS CARTELET - LE 23 JUILLET A 11H', 'Tous les Hommes est un récit de voyage au cœur de notre histoire commune et de nos passions intimes. Emmanuel Brault nous embarque à travers la galaxie et la littérature à la rencontre de trois hommes solitaires dont les amours et les déchirements vont conduire à la naissance d’une nouvelle révolution. Avec Le Livre de Nathan, Nicolas Cartelet explore notre fascination presque sacrée pour les livres et le pouvoir de la fiction sur le monde. Un regard puissamment malicieux, parfois piquant, sur cette passion romanesque capable de transformer les rêves d’un écrivain en réalité. Emmanuel Brault est un ancien juriste, il est aujourd', '16-07-2023'),
(5, 'ALAIN BARATON RACONTE LA ROSE - LE 29 JUILLET A 11H', 'Surnommée « la reine des fleurs » depuis l’Antiquité, la rose règne sans partage : elle est la plus offerte au monde. En l’associant à l’amour dès son apparition, en Perse, nous lui avons prêté une passion que nous la chargeons de transmettre, ce qu’elle accomplit avec charme et fugacité, douceur et piquant. Tout ceci, et bien d’autres découvertes encore, nous attendent dans Le Livre de la rose, où, alliant botanique, histoire et anecdotes, Alain Baraton révèle les secrets de la fleur aux cent pétales. Alain Baraton est jardinier, écrivain, chronique de télévision et de radio. Il est le jardinier en chef du domaine national de Trianon et du parc du château de Versailles, ainsi que le responsable du domaine national de Marly-le-Roi.', '16-07-2023');

-- --------------------------------------------------------

--
-- Table structure for table `commentaires`
--

DROP TABLE IF EXISTS `commentaires`;
CREATE TABLE IF NOT EXISTS `commentaires` (
  `id_compte` int NOT NULL,
  `id_livre` int NOT NULL,
  `texte` text NOT NULL,
  `date` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `commentaires`
--

INSERT INTO `commentaires` (`id_compte`, `id_livre`, `texte`, `date`) VALUES
(2, 3, 'Moi aussi', '16-07-2023'),
(1, 39, 'teeest', '17-07-2023'),
(1, 15, 'test', '16-07-2023'),
(1, 10, 'ok', '17-07-2023');

-- --------------------------------------------------------

--
-- Table structure for table `comptes`
--

DROP TABLE IF EXISTS `comptes`;
CREATE TABLE IF NOT EXISTS `comptes` (
  `id_compte` int NOT NULL AUTO_INCREMENT,
  `prenom` varchar(255) NOT NULL,
  `nom` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `identifiant` varchar(255) NOT NULL,
  `mot_de_passe` varchar(255) NOT NULL,
  `date_inscription` varchar(255) NOT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  `image_perso` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_compte`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `comptes`
--

INSERT INTO `comptes` (`id_compte`, `prenom`, `nom`, `email`, `identifiant`, `mot_de_passe`, `date_inscription`, `is_admin`, `image_perso`) VALUES
(1, 'Louis', 'Thidet', 'louis.thidet@gmail.com', 'louis.thidet', 'admin', '07-07-2023', 1, 1),
(2, 'Lucie', 'Delay', 'luciedg62@gmail.com', 'lucie.delay', 'admin', '14-07-2023', 1, 1),
(3, 'test', 'user', 'test@user', 'test_utilisateur', 'user', '15-07-2023', 0, 0),
(5, 'Bernard', 'Jean', 'bernardjean@mailfictif.com', 'bernardjean', 'jeanbernard123', '16-07-2023', 0, 1),
(6, 'zdazad', 'zadaz', 'dazdazd@adzaazd', 'azddazzd', 'azdazdazdazdadz', '16-07-2023', 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `livres`
--

DROP TABLE IF EXISTS `livres`;
CREATE TABLE IF NOT EXISTS `livres` (
  `id_livre` int NOT NULL AUTO_INCREMENT,
  `titre` varchar(255) NOT NULL,
  `auteur` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `prix` float NOT NULL,
  `categorie` varchar(255) NOT NULL,
  `mots_cles` varchar(255) NOT NULL,
  `editeur` varchar(255) NOT NULL,
  `nb_pages` int NOT NULL,
  `format` varchar(255) NOT NULL,
  `largeur` float NOT NULL,
  `longueur` float NOT NULL,
  `epaisseur` float NOT NULL,
  `poids` float NOT NULL,
  `EAN` bigint NOT NULL,
  `ISBN` bigint NOT NULL,
  PRIMARY KEY (`id_livre`)
) ENGINE=MyISAM AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `livres`
--

INSERT INTO `livres` (`id_livre`, `titre`, `auteur`, `description`, `prix`, `categorie`, `mots_cles`, `editeur`, `nb_pages`, `format`, `largeur`, `longueur`, `epaisseur`, `poids`, `EAN`, `ISBN`) VALUES
(1, 'Oeuvres philosophiques complètes', 'Saint Augustin', 'Né en 354 dans l’Afrique Romaine, Augustin se convertit au christianisme à 32 ans après une vie agitée. Il se retire dans la solitude et se consacre à de la philosophia afin de grandir dans la connaissance de l’Absolu. Ses premières œuvres ont un tel impact et le rendent si célèbre que le peuple le réclame comme prêtre : on l’oblige à sortir de sa retraite et il est ordonné prêtre à 37 ans, puis évêque d\'Hippone à 42 ans. Il meurt à Hippone en 430, tandis que l’Empire s’effondre et que se prépare le Concile d\'Ephèse. Auteur d’une œuvre puissante et inégalable, il est certainement le seul homme dont on puisse dire que sa pensée eut plus d\'influence sur l’histoire que celles de Platon et d’Aristote. Nombreux sont les grands hommes qui voient en saint Augustin, et comme dit l’Eglise elle-même, l’un des plus grands génies qui aient paru sur la terre.', 89.99, 'Philosophie', 'saint-augustin, spiritualité, philosophie, religion, christianisme, platonisme', 'Les Belles Lettres', 4628, 'Relié', 18, 24, 10, 2000, 1957901392607, 6852325516),
(2, 'Romans de la Table ronde', 'Chrétien de Troyes', 'Le roi Arthur et les chevaliers de la Table Ronde. Les merveilles de Bretagne et de Brocéliande. Les amours de Lancelot et de la reine Guenièvre. Perceval en quête du Graal. Ces récits, qui aujourd\'hui encore enßamment l\'imagination et inspirent écrivains, musiciens, cinéastes, ont été contés il y a plus de huit siècles par un des premiers et des plus grands romanciers français, Chrétien de Troyes. Ils fournissent la matière de ses cinq romans, réunis et traduits en français moderne dans ce volume. Les amateurs de littérature celtique trouvent chez lui abondamment leur compte. Mais ils trouvent plus que des récits mystérieux, des amours et des combats, des chevaliers, des fées et des géants, des châteaux et des forêts. Ils trouvent des romans si subtils et si profonds que l\'on n\'a jamais Þni de les approfondir et de les comprendre. Des romans qui ne boudent pas le plaisir de l\'aventure et y ajoutent celui d\'en deviner le sens. Des romans qui donnent à penser autant qu\'à rêver.', 7.7, 'Roman ou nouvelles', 'moyen âge, amour courtois', 'Le Livre de Poche', 734, 'Broché', 3.7, 17, 10, 363, 632374863079, 1153873153697),
(3, 'Madame Bovary', 'Gustave Flaubert', 'C\'est l\'histoire d\'une femme mal mariée, de son médiocre époux, de ses amants égoïstes et vains, de ses rêves, de ses chimères, de sa mort. C\'est l\'histoire d\'une province étroite, dévote et bourgeoise. C\'est, aussi, l\'histoire du roman français. Rien, dans ce tableau, n\'avait de quoi choquer la société du Second Empire. Mais, inexorable comme une tragédie, flamboyant comme un drame, mordant comme une comédie, le livre s\'était donné une arme redoutable : le style. Pour ce vrai crime, Flaubert se retrouva en correctionnelle. Aucun roman n\'est innocent : celui-là moins qu\'un autre. Lire Madame Bovary, au XXIᵉ siècle, c\'est affronter le scandale que représente une oeuvre aussi sincère qu\'impérieuse. Dans chacune de ses phrases, Flaubert a versé une dose de cet arsenic dont Emma Bovary s\'empoisonne : c\'est un livre offensif, corrosif, dont l\'ironie outrage toutes nos valeurs, et la littérature même, qui ne s\'en est jamais vraiment remise.', 4.1, 'Roman ou nouvelles', 'réalisme, flaubert', 'Folio', 528, 'Broché', 17, 10, 2, 290, 8521357992850, 4121045775736),
(4, 'Trois Contes', 'Gustave Flaubert', 'En 1875, incompris depuis Salammbô, enlisé dans les ratures de Bouvard et Pécuchet, ruiné par sa nièce, Flaubert reprend un projet de jeunesse : La Légende de saint Julien l\'Hospitalier. Le feu de l\'écriture lui redonne goût à la vie et à la création : il poursuit avec deux autres récits, pour réunir en une seule oeuvre \" du Moderne, du Moyen Age et de l\'Antiquité \". Un coeur simple, le volet \" moderne \" du triptyque, raconte la vie pathétique de Félicité, une pauvre servante au grand coeur. Coloré et étincelant comme un vitrail, énigmatique comme un rêve, le conte médiéval La Légende de saint Julien l\'Hospitalier retrace le destin sanglant d\'un héros qui oscille entre sainteté et folie. Quant au volet \" antique \", il fait revivre, avec Hérodias, l\'époque évangélique, en donnant à la littérature la première incarnation d\'un mythe qui, de Wilde à Nabokov, traversera la modernité : celui de Salomé. Dernière oeuvre publiée par Flaubert de son vivant, ces Trois Contes peuvent être tenus pour son testament esthétique. Interview : \" François Bégaudeau, pourquoi aimez-vous Trois Contes ? \"', 3, 'Roman ou nouvelles', 'contes, flaubert', 'Flammarion', 208, 'Broché', 10, 17, 1.3, 172, 2642349864555, 6832073315764),
(5, 'Nouvelles de Petersbourg', 'Nicolas Gogol', 'L\'assesseur du collège Kovaliov se réveilla d\'assez bonne humeur. Il s\'étira et se fit donner un miroir dans l\'intention d\'examiner un petit bouton qui, la veille au soir, lui avait poussé sur le nez. A son immense stupéfaction, il s\'aperçut que la place que son nez devait occuper ne présentait plus qu\'une surface lisse ! tout alarmé, Kovaliov se fit apporter de l\'eau et se frotta les yeux avec un essuie-mains : le nez avec bel et bien disparu !... Il s\'habilla séance tenante et se rendit tout droit chez le maître de police. \" Kovaliov retrouvera son nez à la suite d\'aventures fort étranges. Et si, conclut Gogol, \" ce qu\'il y a de plus étrange, c\'est qu\'un auteur puisse choisir de pareils sujets \", vous aurez beau dire, des aventures comme cela arrivent en ce monde, c\'est rare, mais cela arrive.', 5.5, 'Roman ou nouvelles', 'littérature russe, nouvelles, xixe', 'Folio', 320, 'Broché', 10, 17, 2, 10, 3551912112799, 7008093634961),
(6, 'L\'Imitation de Jésus-Christ', 'Thomas a Kempis', 'L’Imitation de Jésus-Christ tient une grande place dans la littérature chrétienne. Écrit par un moine, Thomas a Kempis, durant la première moitié du XVe siècle, ce petit livre a été lu et médité par des générations de laïcs désireux d’approfondir leur vie intérieure.\r\n\r\nL’Imitation est certes un témoignage parmi d’autres du renouveau spirituel de son époque, désigné sous le nom de Devotio moderna, qui oppose la voie de l’intériorisation à un monde extérieur déchiré et violent. Mais les grandes œuvres débordent le temps et le lieu qui ont offert le cadre, le sujet, l’occasion, l’auditeur. C’est l’existence chrétienne de toutes les époques qui est décrite dans ce livre. La grâce et la tentation sont ressaisies à leur « racine » : l’existence de l’amour et du mal. De l’un et de l’autre, l’auteur décrit avec minutie les formes en appelant le lecteur à la conversation intérieure. L’Imitation tend avant tout à cette purification du cœur sans laquelle ne peut être ni compris ni vécu l’Évangile.', 9.5, 'Autre', 'religion, christianisme, spiritualité', 'Seuil', 510, 'Broché', 10, 16, 2, 400, 4134981691734, 819700982818),
(7, 'Œuvres complètes', 'Aristote', 'Il n’est pas une branche du savoir de son temps qu’Aristote n’ait étudiée : de la logique à la rhétorique en passant par la dialectique, de la physique et la chimie à la cosmologie, de la métaphysique et la théologie aux mathématiques, de la politique et l’éthique à la psychologie, sans oublier le très important corpus biologique et le recueil des différentes constitutions qu’il avait compilées avec ses élèves.\r\nOn redécouvre aujourd’hui l’importance du « maître de ceux qui savent » tant pour l’Occident chrétien que pour l’Orient islamique, et l’on trouve un fondement aristotélicien à presque toutes nos sciences dites « humaines ».', 79, 'Philosophie', 'aristote, grèce, réalisme philosphique, philosophie', 'Flammarion', 2928, 'Relié', 18, 25, 7, 2500, 1809962413249, 1576974291292),
(8, 'Hérodote - Thucydide : Oeuvres ', 'Hérodote, Thucydide', '\"Hérodote est le \"père de l\'histoire\", on l\'a dit et répété depuis Cicéron, et on doit encore en convenir. Mais on sait aussi qu\'il est plus d\'une façon d\'écrire l\'histoire, et toute l\'historiographie de l\'Antiquité se laisse assez facilement répartir en deux grandes tendances remontant à Hérodote et Thucydide. Cosmopolite, accusé par Plutarque de sympathie pour les \"barbares\", enquêteur d\'une inlassable curiosité, moins étroitement intéressé à la seule histoire politique, Hérodote est revenu à la mode. Hautain, sûr de l\'éternité de son oeuvre coulée dans l\'airain d\'une langue superbe, Thucydide garde ses fidèles. On a découvert qu\'il avait lui aussi ses passions, ses partis pris ; sans doute y a-t-il gagné de devenir plus proche, plus vivant, sans cesser d\'être grand.\"Jean-Louis Ferrary.', 67.62, 'Histoire', 'histoire, grèce, grèce antique, voyage', 'Gallimard', 1904, 'Relié', 11, 18, 4.7, 700, 2106144155889, 1315343204179),
(9, 'Voyages dans les mondes connus et inconnus - Tome 1, L\'Afrique ', 'Jules Verne', 'Dire la Terre, toute la Terre : les romans de Jules Verne se lisent, de son propre aveu, comme une \" géographie universelle pittoresque \". Partons donc pour un tour du monde inédit, au fil d\'une des oeuvres les plus mythiques de notre littérature.', 32, 'Roman ou nouvelles', 'aventure, voyage', 'Robert Laffont', 1151, 'Broché', 13.2, 19.7, 3.2, 644, 839362324987, 5353486561193),
(10, 'Voyages dans les mondes connus et inconnus - Tome 2, La Méditerranée', 'Jules Verne', 'Après Les cinq périples africains parus dans Bouquins en 2021, pour la première fois rassemblés dans ce second volume d\'une série de cinq, cinq randonnées trépidantes aux quatre coins de la Méditerranée.', 32, 'Roman ou nouvelles', 'aventure, voyage, verne', 'Robert Laffont', 1056, 'Broché', 13.2, 19.7, 3.2, 676, 3570471894639, 798743297374),
(11, 'Ce côté obscur du peuple', 'Pascal Ory', 'Pascal Ory est professeur émérite des universités à la Sorbonne (Paris 1). Il a aussi enseigné, entre autres, à l’École des Hautes Études en sciences sociales, à l’École supérieure de Guerre, à l’INA, aux Langues O’ et à Sciences Po Paris.', 32, 'Essai', 'politique, essai, démocratie, fascisme', 'Robert Laffont', 992, 'Broché', 13.2, 19.7, 3.2, 630, 9170607332362, 2287187284836),
(12, 'Napoléon', 'Jean Tulard', 'Après le coup d’État de Brumaire, Bonaparte affirme  : «  Je suis la Révolution  », pour ajouter «  La Révolution est finie  ». Trois voies sont alors offertes  : le retour au système monarchique, la consolidation des conquêtes bourgeoises et paysannes ou la satisfaction des aspirations des sans-culottes parisiens.\r\nBiographie traditionnelle mais aussi ouvrage de référence, ce Napoléon ou le mythe du sauveur aura été le premier à faire mentir Stendhal quand il prophétisait  : «  D’ici à cinquante ans, il faudra refaire l’histoire de Napoléon tous les ans.  » Il est en effet devenu un véritable classique dont nul ne saurait se passer.\r\nAugmentée de nouvelles annexes, d’une chronologie et d’une filmographie, cette édition est en outre enrichie des recherches les plus récentes menées par les historiens sur tout ce qui touche la France du début du xixe  siècle et la geste napoléonienne.', 10, 'Histoire', 'napoléon, histoire, révolution française', 'Fayard', 512, 'Broché', 18, 11, 2, 458, 7017628344520, 436870642616),
(13, 'Une vision du monde', 'Hubert Vedrine', 'Hubert Védrine, conseiller diplomatique, porte-parole et Secrétaire général de l\'Elysée, puis ministre des Affaires étrangères, sous les présidences Mitterrand et Chirac, à l’orée du XXIe siècle, est reconnu en France et dans le monde comme l’un des meilleurs experts de la géopolitique et des relations internationales', 32, 'Essai', 'politique, diplomatie, autobiographie', 'Robert Laffont', 864, 'Broché', 19.7, 13.2, 3.2, 580, 4557449517010, 4876802380098),
(14, 'L\'Homme sans qualités, tome 1', 'Robert Musil', 'Rien moins qu\'un livre-monument, conçu à la manière d\'une cathédrale. D\'abord publié entre 1931 et 1933, du vivant de Robert Musil, L\'Homme sans qualités est resté inachevé. L\'écrivain autrichien meurt en 1942, laissant derrière lui un vaste chantier de plusieurs milliers de pages (exploitées ensuite avec plus ou moins de bonheur par les éditeurs). À l\'origine, le texte devait se composer de deux volumes, étendus sur quarante ans, principe repris dans cette collection (voir tome 2). Cet \"homme sans qualités\", c\'est un homme sans caractère propre – loin du roman traditionnel – l\'édification de tous les possibles, des hypothèses, à travers plusieurs personnages, qui ont valeur universelle. Ironie, satire, anti-intellectualisme, comédie, tout se fond et se confond entre narration et réflexion philosophique, pour former, selon Philippe Jaccottet, son traducteur, \"un essai de roman\". Avec Les Désarrois de l\'élève Törless et Les Exaltés, c\'est bien l\'œuvre qui a imposé Musil au monde littéraire, après sa mort… --Céline Darner', 15, 'Roman ou nouvelles', 'société, inachevé, autriche, allemagne, 20ème siècle', 'Points', 864, 'Broché', 10, 18, 2, 500, 4348903499907, 2774914982925),
(15, 'L\'Homme sans qualités, tome 2', 'Robert Musil', 'Dans ce roman, qui comporte jusqu\'ici 1 800 pages, Musil a pour principe de choisir de minces coupes de vie qu\'il modèle en profondeur et donne à sa description du monde une ampleur universelle. Le livre a été salué dès sa parution comme une des grandes œuvres du roman européen. Sous prétexte de décrire la dernière année de l\'Autriche, on soulève les questions essentielles de l\'existence de l\'homme moderne pour y répondre d\'une manière absolument nouvelle, pleine à la fois de légèreté ironique et de profondeur philosophique. Narration et réflexion s\'équilibrent parfaitement, de même que l\'architecture de l\'immense ensemble et la plénitude vivante des détails.', 15, 'Roman ou nouvelles', 'société, inachevé, autriche, allemagne, 20ème siècle, philosophie', 'Points', 1090, 'Broché', 10.9, 18, 3.5, 600, 7378111811857, 680310079418),
(16, 'Ombres sur l\'Hudson', 'Isaac Bashevis Singer', 'Rien ne sera plus comme avant pour ces survivants venus de Pologne qui se retrouvent à New York en 1947.\r\nAlors ils sont saisis d\'une folle envie d\'agir, d\'aimer, d\'entreprendre, de réussir. D\'aimer, surtout.\r\nAu centre du roman, Grein, pris entre trois femmes : la sienne, sa maîtresse et Anna, fantasque et irrésistible.\r\nPour pouvoir vivre ensemble, Grein et Anna défient leur entourage, au risque de briser des vies et de se détruire mutuellement.\r\nC\'est au plus profond du cœur humain que nous entraîne Ombres sur l\'Hudson, au cœur de l\'amour, de la passion, de l\'angoisse, du désespoir et parfois de la folie.\r\nDe la lecture de cet immense roman, nul ne sortira indemne.', 13.5, 'Roman ou nouvelles', 'histoire, philosophie, yiddish, judaisme, Pologne, 20ème siècle, littérature américaine, prix nobel de littérature, états-unis', 'Folio', 915, 'Broché', 9.5, 18, 3.8, 500, 4396091773093, 2239135069169),
(17, 'Keila la Rouge', 'Isaac Bashevis Singer', 'À trente-deux ans, Yarmi comptait déjà quatre séjours à la prison de Pawiak pour vol – sa spécialité étant de forcer les serrures. Il avait aussi été arrêté plusieurs fois pour traite des blanches. À vingt-neuf ans, Keila la Rouge s’était successivement distinguée dans trois bordels, un rue Krochmalna, un rue Smocza et un rue Tomkes. »\r\nDans ce grand roman inédit, le conteur malicieux de la rue Krochmalna, le magicien des synagogues et des bordels, ressuscite le monde disparu de la culture yiddish, un monde de couleurs vives qui devint après la guerre un monde gris de cendres.', 9.2, 'Roman ou nouvelles', 'yiddish, judaisme, prix nobel de littérature, Pologne, états-unis, 20ème siècle, amour, prostitution', 'Le Livre de Poche', 432, 'Broché', 10.9, 17.8, 1.9, 200, 8739894964871, 6237551942402),
(18, 'Shosha', 'Isaac Bashevis Singer', 'Varsovie, 1939. Pour la communauté juive de Pologne, le temps des dernières illusions est passé. Le drame qui se prépare va tout emporter, tout détruire. Le jeune Arele Greidinger - qui ressemble comme un frère à Isaac Bashevis Singer à vingt-cinq ans - fait comme tout le monde : il vit \" comme si \". Comme si le succès était quelque chose d\'important, comme si on pouvait encore tomber amoureux, comme si demain existait... Arele a publié un livre que tout le monde lit à Varsovie. Alors qu\'il travaille sur une pièce, sa principale actrice, Betty, qui est américaine, lui propose de l\'épouser. Mais Arele a retrouvé Shosha, une petite amie d\'enfance qu\'il n\'avait jamais réussi à oublier. Enfantine, fragile - arriérée, disent certains - Shosha va incarner toute la pureté, la fraîcheur, l\'innocence dont il rêvait sous ses allures de jeune Don Juan blasé. On retrouve dans ce roman l\'univers familier d\'Isaac Bashevis Singer ; peuplé de rabbis miraculeux, de sages et de fous, de savants talmudistes et de jeunes révolutionnaires, il est comme \" illuminé de l\'intérieur \", transfiguré par la présence de la petite Shosha.', 9.2, 'Roman ou nouvelles', 'seconde guerre mondiale, amour, yiddish, judaisme, Pologne, prix nobel de littérature, varsovie', 'Le Livre de Poche', 408, 'Broché', 11, 17.8, 1.8, 300, 2950038648587, 1289543939640),
(19, 'Portnoy et son complexe', 'Philip Roth', 'Peut-être que si nous posions la question suivante à Alex Portnoy : \"Si vous deviez tirer un trait sur une partie de votre anatomie, laquelle choisiriez-vous ?\", il nous répondrait : \"Mes organes génitaux, mon schlong en yiddish\"... juste avant de changer d\'avis. Pourtant, la sexualité c\'est bien le problème d\'Alex... Brillant élève puis cadre supérieur en vue, écrasé par l\'autorité de ses parents si démesurément attachés à la tradition juive américaine, Alex n\'en reste pas moins un obsédé.\r\nEt les terribles fantasmes qui le hantent vont s\'avérer être les plus lourds fardeaux qu\'un homme élevé dans le quartier israélite de Newark ait à supporter...\r\nAvec cet humour ravageur qui hésite à choisir son camp, la tendresse ou le cynisme, Philip Roth s\'attaque à l\'ignorance et à la bêtise qui nourrit les préjugés. Il le fait sans aucune retenue ni aucune pitié pour dresser comme un étendard le témoignage de Portnoy, un cri désespéré pour la tolérance.\r\nAvec ce plongeon osé dans la sexualité, Philip Roth s\'offre un coup d\'éclat littéraire et un passeport pour la renommée... Hector Chavez', 9.2, 'Roman ou nouvelles', 'Philip Roth, 20ème siècle, littérature américaine, sexualité, humour, psychanalyse, adolescence, judaisme', 'Folio', 384, 'Broché', 10.9, 17.8, 1.5, 218, 4965979787346, 1661192612018),
(20, 'La tache', 'Philip Roth', 'À la veille de la retraite, un professeur de lettres classiques, accusé d\'avoir tenu des propos racistes envers ses étudiants, préfère démissionner plutôt que de livrer le secret qui pourrait l\'innocenter.\r\nTandis que l\'affaire Lewinski défraie les chroniques bien-pensantes, Nathan Zuckerman ouvre le dossier de son voisin Coleman Silk et découvre derrière la vie très rangée de l\'ancien doyen un passé inouï. celui d\'un homme qui s\'est littéralement réinventé, et un présent non moins ravageur : sa liaison avec la sensuelle Faunia, femme de ménage et vachère de trente-quatre ans, prétendument illettrée, et talonnée par un ex-mari vétéran du Vietnam obsédé par la vengeance et le meurtre.\r\nAprès \"Pastorale américaine\" et \"J’ai épousé un communiste\", \"La tache\", roman brutal et subtil, complète la trilogie de Philip Roth sur l\'identité de l\'individu dans les grands bouleversements de l\'Amérique de l\'après-guerre, où tout est équivoque et rien n’est sans mélange, car la tache « est en chacun, inhérente, à demeure, constitutive, elle qui préexiste à la désobéissance, qui englobe la désobéissance, défie toute explication, toute compréhension. C\'est pourquoi laver cette souillure n\'est qu\'une plaisanterie de barbare et le fantasme de pureté terrifiant »', 9, 'Roman ou nouvelles', 'Philip Roth, 21ème siècle, littérature américaine, états-unis, 20ème siècle, secrets, identité, racisme', 'Folio', 496, 'Broché', 11, 17.7, 2, 260, 8342550381428, 6507569110139),
(21, 'Fictions', 'Jorge Luis Borges', 'Sans doute y a-t-il du dilettantisme dans ces Fictions, jeux de l\'esprit et exercices de style fort ingénieux. Pourtant, le pluriel signale d\'emblée qu\'il s\'agit d\'une réflexion sur la richesse foisonnante de l\'imagination. Au nombre de dix-huit, ces contes fantastiques révèlent, chacun à sa manière, une ambition totalisante qui s\'exprime à travers de nombreux personnages au projet démiurgique ou encore à travers La Bibliothèque de Babel, qui prétend contenir l\'ensemble des livres, existants ou non. La multitude d\'univers parallèles et d\'effets de miroir engendrent un \"délire circulaire\" vertigineux, une interrogation sur la relativité du temps et de l\'espace. Dans quelle dimension sommes-nous? Qui est ce \"je\" qui raconte l\'invasion de la cité dans La Loterie de Babylone ? En mettant en vis-à-vis le Quichotte de Ménard et celui de Cervantès, lit-on la même chose ou bien la décision de redire suffit-elle à rendre la redite impossible ? Il n\'est pas certain que l\'on ait envie d\'être relevé du doute permanent qui nous habite au cours de cette promenade dans Le Jardin aux sentiers qui bifurquent. On accepte volontiers d\'être les dupes de ces Artifices, conçus comme le tour le plus impressionnant d\'un prestidigitateur exercé.\r\n-Sana Tang et Léopold Wauters\r\nQuatrième de couverture :\r\n«Maître des splendides possibilités littéraires de la métaphysique considérée comme partie intégrante de l\'univers fantastique, adepte pratiquant de l\'élégante rigueur du genre policier, riche d\'une culture polyphonique peu commune et d\'une formidable intelligence sans failles, joueur dans l\'âme, Borges, dans les contes de Fictions, invente des systèmes à plusieurs degrés, des mondes, des mondes de mondes, labyrinthes de labyrinthes, dans lesquels le réel le plus élémentaire et l\'imaginaire le plus débridé se fondent au sein d\'une harmonie recomposée qui impose au chaos un ordre découvert dans l\'esthétique des miroirs. Le jeu des aventures fantastiques redit sans doute celles du Chevalier cervantin à la Triste Figure, qui, par un avatar à la fois paradoxal et naturel, pourrait bien être l\'un des multiples auteurs de Fictions.Jean Pierre Bernés.', 7.5, 'Roman ou nouvelles', 'nouvelles, fantastique, argentine, amérique du sud, 20ème siècle, philosophie, littérature espagnole, fantastique, magique, labyrinthe, réalisme', 'Folio', 208, 'Broché', 10, 10, 10, 100, 1045820247861, 8851838035629),
(22, 'Mort à crédit', 'Louis-Ferdinand Céline', 'Deuxième grand roman de Louis-Ferdinand Céline, \"Mort à crédit\", publié en 1936, raconte l\'enfance du Bardamu de \"Voyage au bout de la nuit\", paru quatre ans auparavant. Après un prologue situant son présent, médecin dans les années trente, le héros narrateur, Ferdinand, se rappelle ses jeunes années, dans un milieu petit bourgeois, vers 1900. Il est fils unique, élevé dans un passage parisien entre une grand-mère éducatrice fine et intuitive, une mère sacrificielle propriétaire d\'un petit magasin de dentelles et objets de curiosité et un père violent et acariâtre, employé dans une compagnie d\'assurances. Il grandit maladroitement, sans cesse victime des reproches amers de ses parents, multiplie les apprentissages et les échecs sentimentaux et professionnels, séjourne dans un collège anglais avant de voir son destin basculer avec la rencontre d\'un inventeur loufoque, Léonard de Vinci de la fumisterie scientifique, pour vivre des aventures toujours tragi-comiques...\r\nTexte des origines, marqué par le sceau de l\'image maternelle, \"Mort à crédit\" est un parcours initiatique, tout en violence et en émotion, où les souvenirs s\'accompagnent des misères et des révoltes de l\'enfance. C\'est aussi une formidable évocation de Paris au tournant du siècle, drôle et riche de cocasseries irrésistibles, dans un style propre à Céline, fait d\'exclamation, cassant la syntaxe traditionnelle, transposant le parler populaire dru et vert dans le langage écrit.', 10.9, 'Roman ou nouvelles', 'autobiographie, cynisme, enfance, misère, adolescence, france, paris, littérature française, 20ème siècle', 'Gallimard', 622, 'Broché', 10, 10, 10, 10, 5951041771151, 403333793915),
(23, 'L\'éducation sentimentale', 'Flaubert', 'De 1840 à 1867, la vie fait L\'Éducation sentimentale de Frédéric Moreau et de toute une jeunesse idéaliste qui a préparé dans la fièvre la révolution de 1848. Le roman s\'ouvre sur des rêves exaltés et s\'achève sur la médiocrité des uns et des autres. Entre temps, la vie s\'est écoulée autour de Frédéric, qui semble n\'avoir pas plus participé aux mutations de son temps qu\'à l\'édifice de sa propre destinée potentielle. Au cours de cette existence, Madame Arnoux, dont les apparitions sont autant de surgissements mystiques, tient lieu au jeune homme d\'absolu insaisissable. Lui qui rêvait de terres lointaines et d\'ouvrages romantiques déchirants dont il se voyait l\'auteur génial, se retrouve, en guise de destination exotique, à Nogent, la ville de son enfance. Au terme de son parcours, que peut-il faire d\'autre que ponctuer sa conversation avec Deslauriers, le pragmatique non moins malheureux, de \"te souviens-tu\" ? Flaubert éclaire ses personnages d\'une lumière tantôt ironique, tantôt sympathique, et s\'il adopte parfois une vision panoramique des choses, c\'est semble-t-il pour mieux se couler dans l\'esprit de son héros afin de faire vivre au lecteur les velléités de son caractère.\r\nSana Tang-Léopold Wauters', 5, 'Roman ou nouvelles', 'roman d\'apprentissage, roman initiatique, amour, réalisme, romantisme, révolution, politique, france, paris, littérature française, 19ème siècle', 'Flammarion', 624, 'Broché', 10, 17, 3, 430, 6357806638278, 4088102155504),
(24, 'Léon l\'Africain', 'Amin Maalouf', 'Cette autobiographie imaginaire part d\'une histoire vraie. En 1518, un ambassadeur maghrébin, revenant d\'un pèlerinage à la Mecque, est capturé par des pirates siciliens, qui l\'offrent en cadeau à Léon X, le grand pape de la Renaissance.\r\nCe voyageur s\'appelait Hassan al-Wazzan. Il devient le géographe Jean-Léon de Médicis, dit Léon l\'Africain. Sa vie, faite de passions, de dangers et d\'honneurs, et que ponctuent les grands événements de son temps, est fascinante : il se trouvait à Grenade pendant la Reconquista, d\'où, avec sa famille, il a dû fuir l\'Inquistion, en Égypte lors de sa prise par les Ottomans, en Afrique noire à l\'apogée de l\'empire de l\'Askia Mohamed Touré, enfin à Rome aux plus belles heures de la Renaissance, ainsi qu\'au moment du sac de la ville par les soldats de Charles Quint.\r\nHomme d\'Orient et d\'Occident, homme d\'Afrique et d\'Europe, on pouvait difficilement trouver dans l\'histoire personnage dont la vie corresponde davantage à l\'époque étonnante que fut le XVIe siècle.', 8.7, 'Roman ou nouvelles', 'Maalouf, biographie, histoire, religion, islam, voyages, littérature française, afrique, orient, liban, 20ème siècle, renaissance, 16ème siècle', 'Le Livre de Poche', 346, 'Broché', 11, 17, 1.5, 181, 9896058030273, 7407882360548),
(25, 'Samarcande', 'Amin Maalouf', 'Samarcande, c\'est la Perse d\'Omar Khayyam, poète du vin, libre-penseur, astronome de génie, mais aussi celle de Hassan Sabbah, fondateur de l\'ordre des Assassins, la secte la plus redoutable de l\'Histoire.\r\nSamarcande, c\'est l\'Orient du XIXe siècle et du début du XXe, le voyage dans un univers où les rêves de liberté ont toujours su défier les fanatismes. Samarcande, c\'est l\'aventure d\'un manuscrit qui, né au XIe siècle, égaré lors des invasions mongoles, est retrouvé des siècles plus tard.\r\nUne fois encore, nous conduisant sur la route de la soie à travers les plus envoûtantes cités d\'Asie, Amin Maalouf nous ravit par son extraordinaire talent de conteur.\r\nA la suite d\'Edgar Allan poe, il nous dit: \"Et maintenant, promène ton regard sur Samarcande! N\'est-elle pas reine de la Terre? Fière, au-dessus de toutes les villes, et dans ses mains leurs destinées?\"\r\nSamarcande a obtenu le Prix des Maisons de la Presse 1988.\r\n\r\nDepuis bien longtemps que Samarcande fascine les peuples de la terre et plus spécialement ceux de l\'Occident jadis la route de la soie la ville était très prospère dans la culture et bien d\'autres choses ...', 7.7, 'Roman ou nouvelles', 'Maalouf, poésie, biographie, histoire, islam, littérature française, orient, liban, 20ème siècle, perse, moyen-âge', 'Le Livre de Poche', 376, 'Broché', 11, 17.8, 1.3, 168, 4843337427240, 507318470982),
(26, 'Le rocher de Tanios', 'Amin Maalouf', 'Le destin passe et repasse à travers nous, comme l\'aiguille du cordonnier à travers le cuir qu\'il façonne.» Pour Tanios, enfant des montagnes libanaises, le destin se marque d\'abord dans le mystère qui entoure sa naissance : fils de la trop belle Lamia, des murmures courent le pays sur l\'identité de son vrai père.\r\nLe destin passera de nouveau, dans ces années 1830 où l\'Empire ottoman, l’Égypte et l\'Angleterre se disputent ce pays promis aux déchirements, le jour où l\'assassinat d\'un chef religieux contraindra Tanios à l\'exil...\r\nMêlant l\'histoire et la légende, la sagesse et la folie des hommes, le romancier de Léon l\'Africain nous entraîne dans un prodigieux voyage romanesque qui lui a valu le prix Goncourt 1993.\r\nUn merveilleux conteur.\r\nAlain Jacob, Le Monde.\r\nTerre bénie de Dieu, mais hostile aux hommes de bonne volonté, le Liban de Tanios est un mélange d\'eau de fleur d\'oranger et d\'odeur de poudre. En lisant Le Rocher de Tanios, un Orient se rapproche.\r\nChristian Makarian, Le Point.', 7, 'Roman ou nouvelles', 'Maalouf, histoire, prix goncourt, légendes, contes, empire ottoman, littérature française, littérature arabe, orient, liban, 20ème siècle, 19ème siècle', 'Le Livre de Poche', 280, 'Broché', 10, 17, 2, 136, 6944104738204, 677594597773),
(32, 'Le Mont Damion', 'Andre Dhotel', 'Fâché avec l\'école, chassé par son employeur, Fabien traîne par les campagnes et va son chemin calamiteux comme porté par la certitude que ce dernier le mènera vers quelque lumière. Il apprivoise un loup blessé, recueille un chat, rencontre une fille frappée d\'un mal étrange puis une autre, sauvageonne dans l\'âme, qui lui paraît tout autant inaccessible. Seul sous le ciel, il lance aux nuages sa chanson sans queue ni tête, dans l\'attente d\'une improbable réponse -- jusqu\'au jour où, par-delà les champs et les bois, lui parvient l\'écho d\'un hurlement... De tous les grands romans de Dhôtel (avec \"Le Pays où l\'on n\'arrive jamais\" -- et à la même altitude), le plus intimement accordé à cette sauvagerie secrète en nous qui refuse de tourner le dos à l\'enfance.', 8.5, 'Roman ou nouvelles', 'nature, roman d\'apprentissage, enfance, réalisme, magique,  errance, Ardennes, littérature française', 'Le Livre de Poche', 250, 'Broché', 10, 17, 2, 130, 1039504815867, 4502734129369),
(28, 'Grammaire des civilisations', 'Fernand Braudel', 'À la fin des années cinquante, Fernand Braudel participe aux débats sur les programmes scolaires et milite pour un nouveau projet pédagogique en histoire.\r\nS\'opposant à l\'enseignement traditionnel d\'une histoire-récit débitée en portions chronologiques, Braudel veut proposer aux élèves de terminale, de futurs adultes, un discours fondé sur une vision globale du monde et adapté à la compréhension de l\'actualité.\r\nPrésenter les civilisations mondiales grâce aux différentes sciences sociales, voilà le credo de Braudel qui participe en 1963 à la rédaction du manuel appliquant lenouveau programme.Peine perdue, Braudel ne gagne pas le combat de la réforme : bientôt les civilisations disparaissent des cours et le manuel disparaît de la vente.\r\nSous le titre Grammaire des civilisations, le lecteur retrouve la partie du manuel écrite par Braudel, celle qui a échoué sur les bancs de l\'école. Simple et lumineux, le livre ouvre désormais à tous les portes de l\'histoire du monde.', 12, 'Histoire', 'histoire, civilisation, littérature française, 20ème siècle', 'FLAMMARION', 700, 'Broché', 10, 17, 2, 380, 5507164065333, 9444390561223),
(29, 'La Montagne magique', 'Thomas Mann', 'Un jeune homme, Hans Castorp, se rend de Hambourg, sa ville natale, à Davos, en Suisse, pour passer trois semaines auprès de son cousin en traitement dans un sanatorium. Pris dans l\'engrenage étrange de la vie des \"gens de là-haut\" et subissant l\'atmosphère envoûtante du sanatorium, Hans y séjournera sept ans, jusqu\'au jour où la Grande Guerre, l\'exorcisant, va le précipiter sur les champs de bataille.\r\nChef-d\'œuvre de Thomas Mann, l\'un des plus célèbres écrivains allemands de ce siècle, La Montagne magique est un roman miroir où l\'on peut déchiffrer tous les grands thèmes de notre époque. Et c\'est en même temps une admirable histoire aux personnages inoubliables que la lumière de la haute montagne éclaire jusqu\'au fond d\'eux-mêmes.', 12.9, 'Roman ou nouvelles', 'roman initiatique, maladie, mort, prix nobel de littérature, temps, première guerre mondiale, philosophie, montagnes, allemagne, suisse, littérature allemande, 20ème siècle', 'Le Livre de Poche', 1176, 'Broché', 10, 17, 2, 560, 8761290685709, 8075261824722),
(31, 'Le Joueur d\'échecs', 'Stefan Zweig', 'Czentowic, champion d\'échecs arrogant, esprit borné à outrance, inculte et étonnamment stupide, occupe le premier plan jusqu\'à l\'entrée en scène de Monsieur B. Dès lors que cet aristocrate autrichien s\'intéresse à la partie livrée entre le champion et les passagers amateurs, la direction du texte bascule.\r\nPar un effet de symétrie, la narration se transforme en un face à face tendu entre un esprit brillant et rapide à l\'intelligence abstraite et un cerveau au pragmatisme brutal, incapable de projection véritable. Mise en scène percutante de la résurrection de la folie, cette nouvelle oscille entre ouverture et enfermement.\r\nDans cette avancée implacable de la stupidité destructrice, allégorie de la victoire du nazisme mais aussi chef-d’œuvre de composition, Zweig s\'intéresse peu à la survie du corps, préférant montrer les réactions de l\'esprit, qui trouve un symbole parfait dans ce jeu éminemment intelligent mais désespérément stérile.\r\nPublié en 1943, un an après le suicide de son auteur, Le Joueur d\'échecs fait figure de testament dans l’œuvre de Zweig.', 3, 'Roman ou nouvelles', 'zweig, nouvelles, folie, enfermement, échecs, prisons, psychologie, seconde guerre mondiale, nazisme, autriche, 20ème siècle', 'Le Livre de Poche', 128, 'Broché', 11, 18, 1, 177, 1308515210096, 5286452729465),
(33, 'Lettre d\'une inconnue', 'Stefan Zweig', 'Un amour total, passionnel, désintéressé, tapi dans l’ombre, n’attendant rien en retour que de pouvoir le confesser. Une blessure vive, la perte d’un enfant, symbole de cet amour que le temps n’a su effacer ni entamer. L’être aimé objet d’une admiration infinie mais lucide. Une déclaration fanatique, fiévreuse, pleine de tendresse et de folie. La voix d’une femme qui se meurt doucement, sans s’apitoyer sur elle-même, tout entière tournée vers celui qu’elle admire plus que tout. La voix d’une femme qui s’est donnée tout entière à un homme, qui jamais ne l’a reconnue.\r\nAvec Lettre d’une inconnue, Stefan Zweig pousse plus loin encore l’analyse du sentiment amoureux et de ses ravages, en nous offrant un cri déchirant d’une profonde humanité. Ici nulle confusion des sentiments : la passion est absolue.', 1.9, 'Roman ou nouvelles', 'zweig, nouvelles, amour, roman épistolaire, drame, passion, femmes, autriche, 20ème siècle', 'Le Livre de Poche', 96, 'Broché', 11, 18, 0.8, 70, 3642240926769, 7474348643133),
(34, 'Histoire de l\'art', 'Ernst Gombrich', 'Histoire de l\'art de E.H. Gombrich est l\'un des ouvrages sur l\'art les plus célèbres et les plus populaires jamais publiés. Depuis plus de cinquante ans, il demeure une introduction inégalée à l\'ensemble du sujet, des premières peintures rupestres à l\'art d\'aujourd\'hui. Dans le monde entier, les lecteurs de tous âges et de tous milieux ont trouvé en Gombrich un véritable maître, qui allie connaiscance et la sagesse à un don unique pour communiquer directement sa profonde affection pour les oeuvres qu\'il décrit. Cette Histoire de l\'art doit sa popularité durable au style simple et direct de l\'auteur. Son but, écrit-il, est \"d\'apporter un certain ordre, une certaine clarté dans l\'abondance de noms propres, de dates, de styles qui compliquent quelque peu les ouvrages plus spécialisée\". Grâce à son intelligence de la psychologie des arts visuels, il nous fait percevoir l\'histoire de l\'art comme \"un enchaînement ininterrompu de traditions encore vivantes\" qui \"relie l\'art de notre temps à celui de l\'âge des pyramides\". ', 29.95, 'Art', 'vulgarisation, art, histoire, 20ème siècle', 'PHAIDON FRANCE', 1050, 'Broché', 12, 19, 4, 740, 7267793327846, 1778388321292),
(37, 'Enéide', 'Virgile', 'Après la chute de sa patrie, le prince troyen Enée entame un long et périlleux voyage qui doit le conduire en Italie où son destin est de fonder Rome. La déesse Junon s’y oppose et tente de le faire périr dans une tempête. Il s’échoue sur les côtes africaines où Didon, la reine de Carthage, s’éprend de lui et le supplie de rester auprès d’elle. Enée ne peut s’y résoudre et quand Didon à l’aurore aperçoit la flotte qui s’éloigne des côtes, elle se plonge dans le sein l’épée de son amant qui, parvenu à l’embouchure du Tibre après plusieurs années d’errance, luttera pour accomplir sa vie et finalement régner sur le Latium. Ecrite vers la fin du ier siècle avant Jésus-Christ, l’épopée latine de l’Enéide s’établit à la même hauteur où les Grecs avaient pu placer l’Iliade et l’Odyssée que Virgile d’ailleurs imite. Mais si, dans ces douze chants qui accueillent le merveilleux comme le tragique, les Romains pouvaient voir un grand récit de fondation, notre culture occidentale, de Didon et Enée de Purcell au «Cygne» où Baudelaire évoque Andromaque, n’a cessé de nous rappeler que l’étoffe humaine de ses héros et l’exception de leurs aventures appartiennent toujours à notre mémoire. Traduction de Maurice Lefaure revue par Sylvie Laigneau. Edition de Sylvie Laigneau.', 10, 'Poésie', 'rome antique, rome, latin, virgile', 'Folio', 512, 'Broché', 2, 17, 10, 300, 15987751465, 326598745254),
(38, 'Oeuvres poétiques et dramatiques', 'Charles Péguy', 'La postérité retient parfois de Péguy l\'efficacité du polémiste, le prophétisme du philosophe de l\'Histoire, le moraliste aigu, l\'anarchiste irréductible ou le socialiste humaniste et, d\'une manière peu discutée, le patriote martyr. Mais le poète, le connaît-on vraiment ? La répétition est l\'arme, redoutable, de sa versification. Elle ne produit pas de radotage. C\'est le martèlement d\'une voix adressée au public que Péguy entend, en quelque sorte, réinventer ; et c\'est sans doute aussi la marque d\'une scansion, qui rejoint la part d\'oralité consubstantielle à presque toute poésie. Henri Meschonnic écrivait de celle de Péguy qu\'elle était une «épopée de la voix». Elle est simple, sans affectation. Si Du Bellay et Corneille sont des modèles, Villon n\'est jamais très loin. Traditionnel, Péguy ?', 78, 'Poésie', 'chartres, péguy', 'Gallimard', 1888, 'Relié', 5, 18, 11, 600, 47867898194, 81747263813),
(39, 'Le Grand Meaulnes', 'Alain-Fournier', 'Le roman d\'Alain-Fournier est enrichi d\'une préface inédite de Pierre Péju et d\'un long portrait de l\'auteur par son ami Jacques Rivière : deux textes permettant de mieux comprendre les circonstances de l\'élaboration du Grand Meaulnes et sa place particulière dans la littérature française.', 2, 'Roman ou nouvelles', 'aventure, adolescence, berry, nostalgie, mélancolie', 'Folio', 212, 'Broché', 10, 17, 2, 150, 3461987458, 1987458742);

-- --------------------------------------------------------

--
-- Table structure for table `livres_souhaites`
--

DROP TABLE IF EXISTS `livres_souhaites`;
CREATE TABLE IF NOT EXISTS `livres_souhaites` (
  `id_livre` int NOT NULL,
  `id_compte` int NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `livres_souhaites`
--

INSERT INTO `livres_souhaites` (`id_livre`, `id_compte`) VALUES
(8, 15),
(1, 15),
(2, 15),
(12, 1),
(14, 3),
(23, 1),
(1, 1),
(34, 1),
(15, 1),
(38, 1);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
